site_name: PQ Toolkit
dev_addr: '0.0.0.0:8000'
nav:
  - 'Home': index.md
  - 'Getting started':
    - 'Prerequisites': getting-started/prerequisites.md
    - 'API Client walkthrough': getting-started/api-client-walkthrough.md
  - 'Raw reference':
    - 'PqToolkitAPIClient': reference/PqToolkitAPIClient.md
    - 'Exceptions': reference/exceptions.md
    - 'Dataclasses': reference/dataclasses.md
theme:
  name: material
  features:
    - content.tabs.link
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
plugins:
- search
- termynal
- mkdocstrings:
    enabled: !ENV [ENABLE_MKDOCSTRINGS, true]
    default_handler: python
    handlers:
      python:
        paths: [../src/pq-toolkit/src]
        options:
          show_root_heading: true
          show_source: true
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
